namespace Spire.Doc.Fields.Shape
{
    using System;

    internal enum PresetTexture
    {
        BlueTissuePaper = 0x10,
        Bouquet = 0x13,
        BrownMarble = 10,
        Canvas = 1,
        Cork = 20,
        Custom = 0xff,
        DarkDownwardDiagonal = 0xd6,
        DarkHorizontal = 0xef,
        DarkUpwardDiagonal = 0xde,
        DarkVertical = 0xe7,
        DashedDownwardDiagonal = 200,
        DashedHorizontal = 0xd8,
        DashedUpwardDiagonal = 0xd0,
        DashedVertical = 0xe0,
        Denim = 2,
        DiagonalBrick = 0xd9,
        Divot = 0xca,
        DottedDiamond = 0xda,
        DottedGrid = 210,
        FishFossil = 6,
        Granite = 11,
        GreenMarble = 8,
        HorizontalBrick = 0xe1,
        LargeCheckerBoard = 0xe3,
        LargeConfetti = 240,
        LargeGrid = 0xd3,
        LightDownwardDiagonal = 0xc6,
        LightHorizontal = 0xcf,
        LightUpwardDiagonal = 0xce,
        LightVertical = 0xc7,
        MediumWood = 0x17,
        NarrowHorizontal = 0xdf,
        NarrowVertical = 0xd7,
        Newsprint = 12,
        Oak = 0x16,
        OutlinedDiamond = 0xeb,
        PaperBag = 5,
        Papyrus = 0,
        Parchment = 14,
        Percent10 = 0xcc,
        Percent20 = 0xd4,
        Percent25 = 220,
        Percent30 = 0xe4,
        Percent40 = 0xec,
        Percent5 = 0xc4,
        Percent50 = 0xc5,
        Percent60 = 0xcd,
        Percent70 = 0xd5,
        Percent75 = 0xdd,
        Percent80 = 0xe5,
        Percent90 = 0xed,
        PinkTissuePaper = 0x11,
        Plaid = 0xf1,
        PurpleMesh = 0x12,
        RecycledPaper = 13,
        Sand = 7,
        Shingle = 0xe2,
        SmallCheckerBoard = 0xdb,
        SmallConfetti = 0xe8,
        SmallGrid = 0xcb,
        SolidDiamond = 0xf3,
        Sphere = 0xf2,
        Stationery = 15,
        Trellis = 0xea,
        Walnut = 0x15,
        WaterDroplets = 4,
        Wave = 0xd1,
        Weave = 0xe9,
        WhiteMarble = 9,
        WideDownwardDiagonal = 230,
        WideUpwardDiagonal = 0xee,
        WovenMat = 3,
        ZigZag = 0xc9
    }
}

