using System;

internal class Class651
{
    internal const string string_0 = "container";
    internal const string string_1 = "urn:oasis:names:tc:opendocument:xmlns:container";
    internal const string string_10 = "application/x-dtbncx+xml";
    internal const string string_11 = "application/xhtml+xml";
    internal const string string_12 = "package";
    internal const string string_13 = "http://www.idpf.org/2007/opf";
    internal const string string_14 = "unique-identifier";
    internal const string string_15 = "guid";
    internal const string string_16 = "xmlns";
    internal const string string_17 = "xsi";
    internal const string string_18 = "http://www.w3.org/2001/XMLSchema-instance";
    internal const string string_19 = "metadata";
    internal const string string_2 = "version";
    internal const string string_20 = "dc";
    internal const string string_21 = "http://purl.org/dc/elements/1.1/";
    internal const string string_22 = "opf";
    internal const string string_23 = "title";
    internal const string string_24 = "creator";
    internal const string string_25 = "identifier";
    internal const string string_26 = "id";
    internal const string string_27 = "language";
    internal const string string_28 = "type";
    internal const string string_29 = "dcterms";
    internal const string string_3 = "rootfiles";
    internal const string string_30 = "RFC3066";
    internal const string string_31 = "manifest";
    internal const string string_32 = "item";
    internal const string string_33 = "href";
    internal const string string_34 = "toc.ncx";
    internal const string string_35 = "spine";
    internal const string string_36 = "itemref";
    internal const string string_37 = "idref";
    internal const string string_38 = "http://www.daisy.org/z3986/2005/ncx/";
    internal const string string_39 = "head";
    internal const string string_4 = "rootfile";
    internal const string string_40 = "meta";
    internal const string string_41 = "name";
    internal const string string_42 = "content";
    internal const string string_43 = "dtb";
    internal const string string_44 = "docTitle";
    internal const string string_45 = "docAuthor";
    internal const string string_46 = "text";
    internal const string string_47 = "ncx";
    internal const string string_48 = @"META-INF\container.xml";
    internal const string string_49 = "navMap";
    internal const string string_5 = "full-path";
    internal const string string_50 = "navPoint";
    internal const string string_51 = "navLabel";
    internal const string string_52 = "src";
    internal const string string_53 = "playOrder";
    internal const string string_54 = "-//NISO//DTD ncx 2005-1//EN";
    internal const string string_55 = "http://www.daisy.org/z3986/2005/ncx-2005-1.dtd";
    internal const string string_6 = "content.opf";
    internal const string string_7 = "media-type";
    internal const string string_8 = "application/oebps-package+xml";
    internal const string string_9 = "application/epub+zip";
}

