// Assembly Spire.Doc, Version 6.1.0.4040

[assembly: System.Reflection.AssemblyKeyName("")]
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level1)]
[assembly: Spire.License.Package("Spire.Office Platinum", "2.9")]
[assembly: Spire.License.ReleaseDate("2018-01-11")]
[assembly: Spire.License.Package("Spire.Office for .NET", "2.9")]
[assembly: Spire.License.Package("Spire.Doc Pro Edition", "6.1")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Runtime.Versioning.TargetFramework(".NETFramework,Version=v4.0", FrameworkDisplayName=".NET Framework 4")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: Spire.License.Package("Spire.Doc Pack", "6.1")]
[assembly: System.Resources.NeutralResourcesLanguage("en-US")]
[assembly: System.Reflection.AssemblyDescription("Release")]
[assembly: System.Reflection.AssemblyCompany("E-iceblue Co., Ltd.")]
[assembly: System.Reflection.AssemblyTitle("Spire.Doc  ")]
[assembly: System.Reflection.AssemblyProduct("Spire.Doc")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyKeyFile("publickey")]
[assembly: jp3E9FF5BED7F5("88888888:1:1:4.9.7500.9484", 1, true)]
[assembly: System.Reflection.AssemblyDelaySign(true)]
[assembly: System.Reflection.AssemblyCopyright("Copyright (c) 2004-2017 E-iceblue Co., Ltd.")]
[assembly: System.CLSCompliant(true)]

