namespace Spire.CompoundFile.Doc.Native
{
    using System;

    [Flags]
    internal enum CSIDL
    {
        CSIDL_ADMINTOOLS = 0x30,
        CSIDL_ALTSTARTUP = 0x1d,
        CSIDL_APPDATA = 0x1a,
        CSIDL_BITBUCKET = 10,
        CSIDL_COMMON_ADMINTOOLS = 0x2f,
        CSIDL_COMMON_ALTSTARTUP = 30,
        CSIDL_COMMON_APPDATA = 0x23,
        CSIDL_COMMON_DESKTOPDIRECTORY = 0x19,
        CSIDL_COMMON_DOCUMENTS = 0x2e,
        CSIDL_COMMON_FAVORITES = 0x1f,
        CSIDL_COMMON_PROGRAMS = 0x17,
        CSIDL_COMMON_STARTMENU = 0x16,
        CSIDL_COMMON_STARTUP = 0x18,
        CSIDL_COMMON_TEMPLATES = 0x2d,
        CSIDL_CONNECTIONS = 0x31,
        CSIDL_CONTROLS = 3,
        CSIDL_COOKIES = 0x21,
        CSIDL_DESKTOP = 0,
        CSIDL_DESKTOPDIRECTORY = 0x10,
        CSIDL_DRIVES = 0x11,
        CSIDL_FAVORITES = 6,
        CSIDL_FLAG_CREATE = 0x8000,
        CSIDL_FLAG_DONT_VERIFY = 0x4000,
        CSIDL_FLAG_MASK = 0xff00,
        CSIDL_FONTS = 20,
        CSIDL_HISTORY = 0x22,
        CSIDL_INTERNET = 1,
        CSIDL_INTERNET_CACHE = 0x20,
        CSIDL_LOCAL_APPDATA = 0x1c,
        CSIDL_MYPICTURES = 0x27,
        CSIDL_NETHOOD = 0x13,
        CSIDL_NETWORK = 0x12,
        CSIDL_PERSONAL = 5,
        CSIDL_PRINTERS = 4,
        CSIDL_PRINTHOOD = 0x1b,
        CSIDL_PROFILE = 40,
        CSIDL_PROGRAM_FILES = 0x26,
        CSIDL_PROGRAM_FILES_COMMON = 0x2b,
        CSIDL_PROGRAM_FILES_COMMONX86 = 0x2c,
        CSIDL_PROGRAM_FILESX86 = 0x2a,
        CSIDL_PROGRAMS = 2,
        CSIDL_RECENT = 8,
        CSIDL_SENDTO = 9,
        CSIDL_STARTMENU = 11,
        CSIDL_STARTUP = 7,
        CSIDL_SYSTEM = 0x25,
        CSIDL_SYSTEMX86 = 0x29,
        CSIDL_TEMPLATES = 0x15,
        CSIDL_WINDOWS = 0x24
    }
}

