namespace Spire.Doc.Documents
{
    using System;

    internal enum CompatibilityOptions
    {
        AlignTablesRowByRow = 0x27,
        AllowSpaceOfSameStyleInTable = 0x36,
        ApplyBreakingRules = 0x2e,
        AutofitLikeWW11 = 0x39,
        CachedColBalance = 0x41,
        ConvMailMergeEsc = 6,
        differentiateMultirowTableHeader = 0x45,
        doNotFlipMirrorIndents = 0x44,
        DontAdjustLineHeightInTable = 0x24,
        DontAllowFieldEndSelect = 0x2d,
        DontAutofitConstrainedTables = 0x38,
        DontBlnSbDbWid = 0x10,
        DontBreakConstrainedForcedTables = 0x3e,
        DontBreakWrappedTables = 0x2b,
        DontMakeSpaceForUL = 0x15,
        DontSnapToGridInCell = 0x2c,
        DontULTrlSpc = 15,
        DontUseAsianBreakRules = 0x30,
        DontUseHTMLParagraphAutoSpacing = 0x23,
        DontUseIndentAsNumberingTabStop = 0x34,
        DontVertAlignCellWithSp = 0x3d,
        DontVertAlignInTxbx = 0x3f,
        DontWrapTextWithPunct = 0x2f,
        enableOpenTypeFeatures = 0x43,
        ExactOnTop = 0x1c,
        ExpShRtn = 14,
        ExtraAfter = 0x17,
        F2ptExtLeadingOnly = 0x12,
        FELineBreak11 = 0x35,
        ForgetLastTabAlign = 0x25,
        FtnLayoutLikeWW8 = 0x22,
        GrowAutoFit = 50,
        HangulWidthLikeWW11 = 0x3b,
        LayoutRawTableWidth = 40,
        LayoutTableRowsApart = 0x29,
        LeaveBackslashAlone = 13,
        LineWrapLikeWord6 = 0x20,
        MapPrintTextColor = 3,
        MWSmallCaps = 0x16,
        NoColumnBalance = 5,
        NoExtLeading = 20,
        NoSpaceRaiseLower = 2,
        NoTabForInd = 1,
        OrigWordTableRules = 9,
        overrideTableStyleFontSizeAndJustification = 0x42,
        PrintBodyBeforeHdr = 0x13,
        PrintMet = 0x1a,
        ShowBreaksInFrames = 11,
        SpLayoutLikeWW8 = 0x21,
        SplitPgBreakAndParaMark = 60,
        SubOnSize = 0x19,
        SuppressSpBfAfterPgBrk = 7,
        SuppressTopSpacing = 8,
        SuppressTopSpacingMac5 = 0x11,
        SwapBordersFacingPgs = 12,
        TruncDxaExpand = 10,
        TruncFontHeight = 0x18,
        UnderlineTabInNumList = 0x3a,
        UseAutospaceForFullWidthAlpha = 0x26,
        UseFELayout = 70,
        UseNormalStyleForList = 0x33,
        UseWord2002TableStyleRules = 0x31,
        UseWord97LineBreakingRules = 0x2a,
        Word11KerningPairs = 0x40,
        WPJust = 0x1f,
        WPSpace = 30,
        WrapTrailSpaces = 4,
        WW11IndentRules = 0x37,
        WW6BorderRules = 0x1b
    }
}

